development:
  port: 9312
  address: 220.181.158.81
  mysql41: 9306
  #configuration_file: "RAILS_ROOT/config/development.sphinx.conf"
  connection_options:
    username: root
    password: asdf1234
    database: webdb
    
